---
- name: Debian - Install NTP
  sudo: true
  apt: name=ntp state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: RedHat - Install NTP
  sudo: true
  yum: name=ntp state=present update_cache=yes
  when: ansible_os_family == "RedHat"
